# Generated by Django 3.1.4 on 2020-12-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201218_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kontak',
            new_name='Modelskontak',
        ),
    ]
