# Generated by Django 3.1.4 on 2020-12-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201219_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelskontak',
            name='email',
        ),
    ]
