# Generated by Django 3.1.4 on 2020-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(choices=[('Teknik Komputer & Jaringan', 'Teknik Komputer & Jaringan'), ('Multimedia', 'Multimedia'), ('Akuntansi', 'Akuntansi')], default='Teknik Komputer & Jaringan', max_length=255)),
            ],
        ),
    ]
