# Generated by Django 3.1.4 on 2021-01-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitas',
            name='tingkat_kelas',
            field=models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default='X', max_length=255),
        ),
        migrations.AlterField(
            model_name='identitas',
            name='kelas',
            field=models.CharField(choices=[('Teknik Komputer & Jaringan', 'Teknik Komputer & Jaringan'), ('Multimedia', 'Multimedia'), ('Akuntansi', 'Akuntansi'), ('Tata Busana', 'Tata Busana'), ('Perbankan Syariah', 'Perbankan Syariah'), ('Tata Boga', 'Tata Boga'), ('TKKR', 'TKKR'), ('OTKP', 'OTKP'), ('BDP', 'BDP'), ('DKV', 'DKV'), ('Animasi', 'Animasi')], default='Teknik Komputer & Jaringan', max_length=255),
        ),
    ]
