# Generated by Django 3.1.4 on 2021-01-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_auto_20210101_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Identitas',
        ),
    ]
