# Generated by Django 3.1.5 on 2021-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_profile', '0003_delete_identitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas_x',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(choices=[('Teknik Komputer & Jaringan', 'Teknik Komputer & Jaringan'), ('Multimedia', 'Multimedia')], default='Teknik Komputer & Jaringan', max_length=255)),
                ('tingkat_kelas', models.CharField(choices=[('X', 'X')], default='X', max_length=255)),
                ('status_siswa', models.CharField(choices=[('aktif', 'aktif')], default='aktif', max_length=255)),
            ],
        ),
    ]
