# Generated by Django 3.1.5 on 2021-01-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_kelas_x'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kelas_x',
        ),
    ]
