# Generated by Django 3.1.4 on 2021-01-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(choices=[('Teknik Komputer & Jaringan', 'Teknik Komputer & Jaringan'), ('Multimedia', 'Multimedia'), ('Akuntansi', 'Akuntansi'), ('Tata Busana', 'Tata Busana'), ('Perbankan Syariah', 'Perbankan Syariah'), ('Tata Boga', 'Tata Boga'), ('TKKR', 'TKKR'), ('OTKP', 'OTKP'), ('BDP', 'BDP'), ('DKV', 'DKV'), ('Animasi', 'Animasi')], default='Teknik Komputer & Jaringan', max_length=255)),
                ('tingkat_kelas', models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default='X', max_length=255)),
            ],
        ),
    ]
