# Generated by Django 3.1.5 on 2021-01-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0002_kelas_siswa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kelas_siswa',
        ),
    ]
