# Generated by Django 3.1.5 on 2021-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0003_delete_kelas_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas_Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TKJ', models.CharField(choices=[('TKJ', 'Teknik Komputer & Jaringan'), ('Multimedia', 'Multimedia'), ('Akuntansi', 'Akuntansi'), ('Tata Busana', 'Tata Busana'), ('Perbankan Syariah', 'Perbankan Syariah'), ('Tata Boga', 'Tata Boga'), ('TKKR', 'TKKR'), ('OTKP', 'OTKP'), ('BDP', 'BDP'), ('DKV', 'DKV'), ('Animasi', 'Animasi')], default='TKJ', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tingkat_Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='identitas',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='identitas',
            name='tingkat_kelas',
        ),
    ]
