# Generated by Django 3.1.5 on 2021-01-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0005_auto_20210104_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas_siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TKJ', models.CharField(choices=[('TKJ', 'Teknik Komputer & Jaringan'), ('MM', 'Multimedia'), ('AKL', 'Akuntansi'), ('TBU', 'Tata Busana'), ('PBKS', 'Perbankan Syariah'), ('TBO', 'Tata Boga'), ('TKKR', 'TKKR'), ('OTKP', 'OTKP'), ('BDP', 'BDP'), ('DKV', 'DKV'), ('ANM', 'Animasi')], default='TKJ', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='identitas',
            name='TKJ',
        ),
    ]
