# Generated by Django 3.1.5 on 2021-01-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0006_auto_20210104_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='tingkat_siswa',
            name='Kelas_x',
            field=models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default='X', max_length=255),
        ),
    ]
