# Generated by Django 3.1.5 on 2021-01-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0009_auto_20210104_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='kelas_siswa',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='nama_siswa',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='tingkat_siswa',
        ),
        migrations.AddField(
            model_name='identitas',
            name='kelas',
            field=models.CharField(choices=[('Teknik Komputer & Jaringan', 'Teknik Komputer & Jaringan'), ('Multimedia', 'Multimedia'), ('Akuntansi', 'Akuntansi'), ('Tata Busana', 'Tata Busana'), ('Perbankan Syariah', 'Perbankan Syariah'), ('Tata Boga', 'Tata Boga'), ('TKKR', 'TKKR'), ('OTKP', 'OTKP'), ('BDP', 'BDP'), ('DKV', 'DKV'), ('Animasi', 'Animasi')], default='Teknik Komputer & Jaringan', max_length=255),
        ),
        migrations.AddField(
            model_name='identitas',
            name='tingkat_kelas',
            field=models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default='X', max_length=255),
        ),
        migrations.DeleteModel(
            name='Kelas_siswa',
        ),
        migrations.DeleteModel(
            name='Siswa',
        ),
        migrations.DeleteModel(
            name='Tingkat_Siswa',
        ),
    ]
