# Generated by Django 3.1.5 on 2021-01-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0011_identitas_status_aktif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitas',
            name='status_aktif',
        ),
        migrations.AddField(
            model_name='identitas',
            name='status_siswa',
            field=models.CharField(choices=[('aktif', 'aktif')], default='aktif', max_length=50),
        ),
    ]
