# Generated by Django 3.1.5 on 2021-01-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_add', '0012_auto_20210106_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitas',
            name='nis_siswa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
